Updating to match where we should be
ERROR: had to add the false flag in default
QUIZ: Added additional stats tests that students will do
QUIZ: Update to use hamcrest
QUIZ: Also added code to get rid of robolectric manifest warning